### PR TITLE
3d projections for a 2d screen

### PR DESCRIPTION
**Pull request by leoscholl**
- add options for 3d projection and anaglyph into gui
- cap cylinder ends

### CODE REVIEW

**Comment by katherineperks** [comment]
I tested the tracking task on this branch and it seems to work fine

**Comment by katherineperks** [comment]
Not sure if any tasks currently used the `Window2D` feature or if someone plans to in the future, but it causes a bug (causes same bug on master branch, so this is a problem I noticed that is not specific to this branch).

**Comment by leoscholl** [comment]
What is the bug?

**Comment by katherineperks** [comment]
Bug when `Window2D` feature is checked off on master branch:
Screenshot from 2024-06-17 15-02-04

**Comment by katherineperks** [comment]
> Not sure if any tasks currently used the `Window2D` feature or if someone plans to in the future, but it causes a bug (causes same bug on master branch, so this is a problem I noticed that is not specific to this branch).

`Window2D` feature not the same as `Window2D` class. So the former is still a bug, but not relevant for this PR

**Pull request merged**
